// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGX1DrxtFzaLm1dlz7yR7t76Kh47AHJy8',
    appId: '1:649282387693:android:a3672b8404a0e65ac0d6e4',
    messagingSenderId: '649282387693',
    projectId: 'solo-leveling-v2',
    databaseURL: 'https://solo-leveling-v2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solo-leveling-v2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCK5YhOvj9hMrr-mgUcjCgpOxoqMpV-WU',
    appId: '1:649282387693:web:8107d914bc498b20c0d6e4',
    messagingSenderId: '649282387693',
    projectId: 'solo-leveling-v2',
    authDomain: 'solo-leveling-v2.firebaseapp.com',
    databaseURL: 'https://solo-leveling-v2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solo-leveling-v2.firebasestorage.app',
    measurementId: 'G-QBQPQFJK67',
  );
}
